### ISSUE TITLE
A link forwards to 404 page

### ISSUE THREAD

**Issue by kulikov98** [EPAM-JS-Competency-center/azure-development-course-initial#13]
I couldn't find a suitable replacement, so instead of PR, I had to create an issue.

https://github.com/EPAM-JS-Competency-center/azure-development-course-initial/blob/873c388515086d651a20c90bc1164eed311bff72/docs/1-project-setup/02-set-up-terraform.md?plain=1#L29

**Comment by Ayzrian** [comment]
Updated. Now it is public repository.

Thanks for flagging that, @kulikov98
